Backend/feature/sign in
se2-2021-tue-16-okulewicz/Project-Group-B pull request #23
Opened 2021-03-16 15:15 UTC by pinola-b

2021-03-16 17:02 UTC, Lank891 commented
Just reminder about assignee, label, project and milestone :D

2021-03-20 12:16 UTC, pinola-b commented
I made a separate table for Shelters, and made a OneToOne connection between DogShelterAccount and Shelter.
Had to create an additional wrapper class for LoginInformation. 

Endpoints for authentication weren't specified (or I am just blind), so I did it as /account/login

2021-03-20 12:19 UTC, pinola-b commented
Would close #13 (Sign-in in backend)

2021-03-20 13:09 UTC, Lank891 requested changes
It is nice, you can make login request and you get the token. But the token is not stored anywhere. You have to store the token (alongside with the permission type like admin/shelter/user). You also need a function (yeah it is not in the spec but it is needed as internal implementation) that will take the token (or whole http header) and check, if token is actually valid and the permission matches (for example it can be a function in login service `boolean IsAuthorized(string token,  UserType requiredPermissions)` (or with headers instead of token, like in carly). Additionally it would be nice (if you won't do it, i'll do it as a separate PR) to add exception for lack of authorisation, handle it to return code 403 (according to api docs) and add it already to existing getting and adding dogs. Obviously then tests must be changed since right now they do not have token and we would need to create some kind of test token for development anyway.

2021-03-20 13:09 UTC, Lank891 commented on Backend/src/test/java/controller/internal/UserControllerTest.java
> +                .andExpect(status().isOk());
This has to be changed obviously after api changes, check not only if it is ok but for example if user type is correct

2021-03-22 15:01 UTC, Lank891 approved these changes
Todo: 
1. Add tests with failed login
2. Add requests authentication

I'll do it in a separate PR just as I said before

2021-03-22 15:09 UTC, merged